//go:generate go install -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
package main

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/portapps/portapps/v3"
	"github.com/portapps/portapps/v3/pkg/log"
	"github.com/portapps/portapps/v3/pkg/utl"
)

var (
	app *portapps.App
)

const (
	vmOptionsFile = "idea.vmoptions"
)

func init() {
	var err error

	// Init app
	if app, err = portapps.New("intellij-idea-ultimate-portable", "IntelliJ IDEA Ultimate"); err != nil {
		log.Fatal().Err(err).Msg("Cannot initialize application. See log file for more info.")
	}
}

func main() {
	ideaExe := "idea64.exe"
	ideaVmOptionsFile := "idea64.exe.vmoptions"

	utl.CreateFolder(app.DataPath)
	app.Process = filepath.Join(app.AppPath, "bin", ideaExe)
	app.WorkingDir = filepath.Join(app.AppPath, "bin")

	// override idea.properties
	ideaPropContent := strings.Replace(`# DO NOT EDIT! AUTOMATICALLY GENERATED BY PORTAPPS.
idea.config.path={{ DATA_PATH }}/config
idea.system.path={{ DATA_PATH }}/system
idea.plugins.path={{ DATA_PATH }}/plugins
idea.log.path={{ DATA_PATH }}/log`, "{{ DATA_PATH }}", utl.FormatUnixPath(app.DataPath), -1)

	ideaPropPath := filepath.Join(app.DataPath, "idea.properties")
	if err := utl.CreateFile(ideaPropPath, ideaPropContent); err != nil {
		log.Fatal().Err(err).Msg("Cannot write idea.properties")
	}

	// https://www.jetbrains.com/help/idea/tuning-intellij-idea.html#configure-platform-properties
	os.Setenv("IDEA_PROPERTIES", ideaPropPath)

	// https://www.jetbrains.com/help/idea/tuning-the-ide.html#configure-jvm-options
	os.Setenv("IDEA_VM_OPTIONS", filepath.Join(app.DataPath, vmOptionsFile))
	if !utl.Exists(filepath.Join(app.DataPath, vmOptionsFile)) {
		utl.CopyFile(filepath.Join(app.AppPath, "bin", ideaVmOptionsFile), filepath.Join(app.DataPath, vmOptionsFile))
	} else {
		utl.CopyFile(filepath.Join(app.DataPath, vmOptionsFile), filepath.Join(app.AppPath, "bin", ideaVmOptionsFile))
	}

	defer app.Close()
	app.Launch(os.Args[1:])
}
