//go:generate go install -v github.com/josephspurrier/goversioninfo/cmd/goversioninfo
//go:generate goversioninfo -icon=res/papp.ico
package main

import (
	"os"
	"runtime"
	"strings"

	. "github.com/portapps/portapps"
)

func init() {
	Papp.ID = "intellij-idea-ultimate-portable"
	Papp.Name = "IntelliJ IDEA Ultimate"
	Init()
}

func main() {
	ideaExe := "idea.exe"
	if runtime.GOARCH == "amd64" {
		ideaExe = "idea64.exe"
	}

	Papp.AppPath = AppPathJoin("app")
	Papp.DataPath = CreateFolder(AppPathJoin("data"))
	Papp.Process = PathJoin(Papp.AppPath, "bin", ideaExe)
	Papp.Args = nil
	Papp.WorkingDir = PathJoin(Papp.AppPath, "bin")

	// override idea.properties
	ideaPropContent := strings.Replace(`# DO NOT EDIT! AUTOMATICALLY GENERATED BY PORTAPPS.
idea.config.path={{ DATA_PATH }}/config
idea.system.path={{ DATA_PATH }}/system
idea.plugins.path={{ DATA_PATH }}/plugins
idea.log.path={{ DATA_PATH }}/log`, "{{ DATA_PATH }}", FormatUnixPath(Papp.DataPath), -1)

	ideaPropPath := PathJoin(Papp.DataPath, "idea.properties")
	if err := CreateFile(ideaPropPath, ideaPropContent); err != nil {
		Log.Errorf("Cannot write idea.properties: %s", err)
	}

	// https://www.jetbrains.com/help/idea/tuning-intellij-idea.html#configure-platform-properties
	OverrideEnv("IDEA_PROPERTIES", ideaPropPath)

	Launch(os.Args[1:])
}
